### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by agriffard** [AidosMarcos/OrchardCoreCafeTheme#2]
Please replace the section in appveyor.yml:
```
  api_key:
      secure: ....
```
On nuget.org, create an account and generate an Api Key, then encrypt it thanks to this tool:
https://ci.appveyor.com/tools/encrypt

**Comment by agriffard** [comment]
On appveyor.com, create an account, then add a project pointing to your github repository.

Each time a commit will be pushed on the master, the process declared in appveyor.yml will be executed and a new version of the package will be upoaded to Nuget.

**Comment by psijkof** [comment]
That's great to know. We were still kicking off a new build manually. Thanks.

**Comment by agriffard** [comment]
See https://www.nuget.org/packages/CafeTheme.OrchardCore/1.0.0-rc-12
I am also struggling to find the correct way to use the version suffix because rc-12 is lower than rc-9 on Nuget.

On https://www.nuget.org/packages/Resume.OrchardCore, I also unlisted the previous ones.
On Appveyor, in the project setting, I also changed the version number to 1000.

**Comment by psijkof** [comment]
Yep I saw that too... gonna fix it.
